version: "3.7"
services:
  clusterer:
    container_name: bs_clusterer
    build: ./clusterer
    image: bs-cl
    volumes:
      - ${IMAGES_DIR:-/images}:/images
    networks:
      - webnet
    environment:
      - RESULTS_FILE=${RESULTS_FILE:-results.pkl}
  frontend:
    container_name: bs_frontend
    build: ./frontend
    image: bs-fr
    volumes:
      - ${IMAGES_DIR:-/images}:/images
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:

